
# Please set your artifact path specified when training
artifact_path: <fill>

dataset:
    type: asap-aes
    params:
        path: /home/manabe_h/workspace/octanove/profiler/data/asap-aes/training_set_rel3.tsv.random11680_rest
        prompt_id: <fill>

output_convert:
    regression_to_classification:
        type: MinMaxDenormalizedRoundNearestInteger
        params:
          x_min: <fill>
          x_max: <fill>

metrics:
    classification:
        - type: MacroF1
          params:
        - type: MicroF1
          params:
        - type: Accuracy
          params:
        - type: QuadraticWeightedKappa
          params:
    regression:
        - type: PearsonCorrelation
          params:
